version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: rifas-doradas-db
    environment:
      POSTGRES_USER: rifas_admin
      POSTGRES_PASSWORD: rifas_secure_password_2024
      POSTGRES_DB: rifas_doradas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - rifas-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: rifas-doradas-backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://rifas_admin:rifas_secure_password_2024@postgres:5432/rifas_doradas
      JWT_SECRET: your-super-secret-jwt-key-change-this
      EMAIL_USER: rifasdoradas@gmail.com
      EMAIL_PASS: your-app-specific-password
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads
    networks:
      - rifas-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rifas-doradas-frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rifas-network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: rifas-doradas-adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - rifas-network
    restart: unless-stopped

volumes:
  postgres_data:
  uploads:

networks:
  rifas-network:
    driver: bridge